config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'examples#index'

  resources :examples, only: [] do
    collection do
      get :click_to_edit
      get :bulk_update
      get :click_to_load
      get :delete_row
    end
  end

  resources :contacts do
    collection do
      put :activate
      put :deactivate
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base; end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: %i[edit update show destroy]
  before_action :find_multiple_contacts, only: %i[activate deactivate]

  # CSRF token authenticity error using htmx-delete
  protect_from_forgery except: [:destoy]

  layout false

  def index
    @contacts = Contact.page(params[:page])
  end

  def show; end

  def edit; end

  def update
    @contact.update(contact_params)

    redirect_back fallback_location: root_path
  end

  def destroy
    @contact.destroy

    head :ok
  end

  def activate
    update_status(status: true)

    render_contact_row
  end

  def deactivate
    update_status(status: false)

    render_contact_row
  end

  private

  def index_params
    params.require(:page)
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :active)
  end

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def find_multiple_contacts
    @contacts = Contact.where(id: params[:ids])
  end

  def update_status(status:)
    Contact.where(id: params[:ids]).update(active: status)
  end

  def render_contact_row
    render(
      template: false,
      partial: 'contacts/contact_row',
      collection: Contact.all,
      as: :contact,
      locals: {
        include_checkbox: true,
        changed_contacts: changed_contacts
      }
    )
  end

  # Pass changed contacts to partial to be able to change tr class and show transitions.
  def changed_contacts
    params[:ids].each_with_object({}) do |id, obj|
      obj[id.to_i] = action_name
    end
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_contacts, only: [:bulk_update, :delete_row]

  def index; end

  def click_to_edit
    @contact = Contact.first
  end

  def bulk_update; end

  def delete_row; end

  private

  def set_contacts
    @contacts = Contact.all
  end

  def click_to_load
    @contacts = Contact.page(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_click_to_load_rows.html.erb
<%= render(
  partial: 'contacts/contact_row',
  collection: contacts,
  as: :contact,
  locals: { include_checkbox: false }
) %>

<tr id="replaceMe">
  <td colspan="3">
    <%= button_tag(
      disabled: contacts.last_page?,
      'hx-get': contacts_path(page: contacts.next_page),
      'hx-target': '#replaceMe',
      'hx-swap': 'outerHTML'
    ) do %>
      Load More Agents...
    <% end %>
  </td>
</tr>

app/views/contacts/_contact.html.erb
<div>
  <label>First Name</label>:
  <%= contact.first_name %>
</div>
<div>
  <label>Last Name</label>:
  <%= contact.last_name %>
</div>
<div>
  <label>Email</label>:
  <%= contact.email %>
</div>

app/views/contacts/_contact_row.html.erb
<% first_td = content_tag(:td) do %>
  <%= check_box_tag 'ids[]', contact.id -%>
<% end %>

<% changed_contacts ||= {} %>
<% klass = changed_contacts[contact.id] ? changed_contacts[contact.id] : '' %>

<tr class="<%= klass %>">
  <%= include_checkbox ? first_td : '' %> 
  <td>
    <%= "#{contact.first_name} #{contact.last_name}" %>
  </td>
  <td>
    <%= contact.email %>
  </td>
  <td>
    <%= contact.active ? 'Active' : 'Inactive' %>
  </td>
</tr>

app/views/contacts/_contact_row_with_delete_button.html.erb
<tr>
  <td>
    <%= "#{contact.first_name} #{contact.last_name}" %>
  </td>
  <td>
    <%= contact.email %>
  </td>
  <td>
    <%= contact.active ? 'Active' : 'Inactive' %>
  </td>
  <td>
    <%= button_tag type: 'button', data: { 'hx-delete' => contact_path(contact) } do %>
      Delete
    <% end %>
  </td>
</tr>

app/views/contacts/_contacts_table.html.erb
<% include_checkbox = false unless defined?(:include_checkbox) %>

<table>
  <thead>
  <tr>
    <%= include_checkbox ? content_tag(:th) : '' %>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody id="tbody">
    <%= render(
      partial: 'contacts/contact_row',
      collection: contacts,
      as: :contact,
      locals: { include_checkbox: include_checkbox }
    ) %>
  </tbody>
</table>

app/views/contacts/_form.html.erb
<%= form_with model: @contact do |form| %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>

  <%= form.label :last_name %>
  <%= form.text_field :last_name %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.submit 'Update' %>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<%= render 'contacts/click_to_load_rows', contacts: @contacts %>

app/views/examples/bulk_update.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'bulk_update', 'data-turbolinks-track': 'reload' %>
<% end %>

<h1>Bulk update</h1>

<h4>Select Rows And Activate Or Deactivate Below</h4>

<div hx-include="#checked-contacts" hx-target="#tbody">
  <button hx-put="<%= activate_contacts_path %>">Activate</button>
  <button hx-put="<%= deactivate_contacts_path %>">Deactivate</button>
</div>

<%= form_with html: { id: 'checked-contacts' } do |form| %>
  <%= render(
    'contacts/contacts_table',
    contacts: @contacts,
    include_checkbox: true
  ) %>
<% end %>

app/views/examples/click_to_edit.html.erb
<h1>Click to edit</h1>

<h4>This pattern provides inline editing without a page refresh</h4>

<div hx-target='this' hx-swap='outerHTML'>
  <%= render @contact %>

  <button hx-get='<%= edit_contact_path(@contact) %>'>
    Click To Edit
  </button>
</div>

app/views/examples/click_to_load.html.erb
<h1>Click to load</h1>

<h4>This example shows how to implement click-to-load the next page in a table of data.</h4>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody id="tbody">
    <%= render 'contacts/click_to_load_rows', contacts: @contacts %>
  </tbody>
</table>

app/views/examples/delete_row.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'delete_row', 'data-turbolinks-track': 'reload' %>
<% end %>

<h1>Delete Row</h1>

<h4>This example shows how to implement a delete button that removes a table row upon completion.</h4>

<table class="table delete-row-example">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
    <%= render(
      partial: 'contacts/contact_row_with_delete_button',
      collection: @contacts,
      as: :contact
    ) %>
  </tbody>
</table>

app/views/examples/index.html.erb
<h1>HTMX examples</h1>

<table>
  <thead>
    <tr>
      <th>Pattern</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to 'Click to edit', click_to_edit_examples_path %>
      </td>
      <td>
        Demonstrates inline editing of a data object
      </td>
    </tr>

    <tr>
      <td>
        <%= link_to 'Bulk edit', bulk_update_examples_path %>
      </td>
      <td>
        Demonstrates bulk updating of multiple rows of data
      </td>
    </tr>

    <tr>
      <td>
        <%= link_to 'Click to load', click_to_load_examples_path %>
      </td>
      <td>
        Demonstrates clicking to load more rows in a table
      </td>
    </tr>

    <tr>
      <td>
        <%= link_to 'Delete row', delete_row_examples_path %>
      </td>
      <td>
        Demonstrates row deletion in a table
      </td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HtmxRailsExamples</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: :all, 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>